name: CI

on:
  pull_request:
  push:
    tags:
      - '*'
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Dependencies
    steps:
      - uses: actions/checkout@v4
      
      - name: PHP setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, curl, dom, json, pdo, mysql, xml, zip
          tools: composer
      
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist
      
      - name: Install gettext
        run: sudo apt-get install -y gettext

  lint:
    runs-on: ubuntu-latest
    name: Code Linting
    needs: build
    steps:
      - uses: actions/checkout@v4
      
      - name: PHP setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, curl, dom, json, pdo, mysql, xml, zip
          tools: composer
      
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist
      
      - name: Install gettext
        run: sudo apt-get install -y gettext
      
      - name: Run code linting
        run: make lint

  test:
    runs-on: ubuntu-latest
    name: Unit & Integration Tests
    needs: build
    steps:
      - uses: actions/checkout@v4
      
      - name: PHP setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, curl, dom, json, pdo, mysql, xml, zip
          tools: composer
      
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist
      
      - name: Install gettext
        run: sudo apt-get install -y gettext
      
      - name: Check untranslated strings
        run: make check-untranslated
      
      - name: Generate .mo file
        run: make compile-mo
      
      - name: Run unit tests
        run: make test
